version: '3.3'

services:

    webserver:
        image: thepaperlessproject/paperless
        restart: unless-stopped
        ports:
            - "8200:8000"
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
            - ./consume:/consume
        environment:
            - PAPERLESS_OCR_LANGUAGES=spa
            - USERMAP_UID=1000
            - USERMAP_GID=1000
        command: ["gunicorn", "-b", "0.0.0.0:8000"]        

    consumer:
        image: thepaperlessproject/paperless
        restart: unless-stopped
        depends_on:
            - webserver
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
            - ./consume:/consume
        command: ["document_consumer"]
        environment:
            - PAPERLESS_OCR_LANGUAGES=spa
            - USERMAP_UID=1000
            - USERMAP_GID=1000
            - PAPERLESS_CONVERT_MEMORY_LIMIT=32000000
            - PAPERLESS_CONVERT_TMPDIR=/var/tmp
        tmpfs:
            - /tmp

volumes:
    data:
    media:
